### ISSUE TITLE
Documentation ?

### ISSUE THREAD

**Issue by luzpaz** [rostskadat/FreeCAD-SH3D#2]
The potential for this workbench is great. Is there a dedicated spot for documentation ?

**Comment by rostskadat** [comment]
Hello @luzpaz,

Thanks for your comment. I started a page on the [Freecad Wiki](https://wiki.freecad.org/FreeCAD-SH3D). However, it lacks content. 
The project's README also provide some user level information
As for the code itself, comments are sparse...

All suggestion / PR are welcome.

**Comment by rostskadat** [comment]
The importer has been moved to the FreeCAD main repo (through PR FreeCAD/FreeCAD #17165)
