### ISSUE TITLE
Is SH3D wb FreeCAD 1.0 compatible? 

### ISSUE THREAD

**Issue by luzpaz** [rostskadat/FreeCAD-SH3D#3]
* https://github.com/FreeCAD/FreeCAD-addons/issues/305

**Comment by rostskadat** [comment]
Hello @luzpaz

Thanks for pointing out the great news of FreeCAD 1.0. I haven't tested whether the WB is compatible with 1.0RC, unfortunately I have limited access to my dev rig until the end of October. If you do not mind I'll keep that issue opened until that time.

Thanks

**Comment by rostskadat** [comment]
Hello @luzpaz 

I confirm that the workbench does work with the FreeCAD 1.0.0RC1 AppImage:

```
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38642 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc1)
Hash: 60a251354e203bdb924e2190fb9f5e18b48d7362
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * FreeCAD-SH3D 0.0.1
```

I'm closing the issue. Please feel free to re-open the issue if more needs to be done regarding that topic.
