### ISSUE TITLE
Possibility to colaborate with the Render WB ?

### ISSUE THREAD

**Issue by luzpaz** [rostskadat/FreeCAD-SH3D#5]
Since SH3D users are used to its convenient scene rendering capabilities perhaps you cna make it possible to streamline rendering through the Render WB through custom shortcuts ? 

If so, you may want to befriend 'howetuft', the current Render wb dev over at https://github.com/FreeCAD/FreeCAD-render

**Comment by rostskadat** [comment]
Hello @luzpaz 

Thanks for your suggestion. Could you share an example of shortcut that you would find useful?
Keep in mind that I'm really new to the Free-CAD project, and my knowledge is limited to the elements I've had to touch to get that first version.

Regards

**Comment by luzpaz** [comment]
For example, having streamlined options to display scenes in different rendering engines right within SH3D workbench?

It may be beneficial to just ping @howetuft directly and ask how other workbenches have utilized RenderWB and even streamlined it's powerful functionality so we don't 'reinvent the wheel' if you will?

**Comment by howetuft** [comment]
Hello,
Well, it should be simple: Render WB is aimed to handle any object existing in FreeCAD. So, once you've imported from SH3D, you should be able to render via Render. If you've got an example of imported SH3D, we can make a test.

**Comment by rostskadat** [comment]
> Hello, Well, it should be simple: Render WB is aimed to handle any object existing in FreeCAD. So, once you've imported from SH3D, you should be able to render via Render. If you've got an example of imported SH3D, we can make a test.

Hello @howetuft 

There are several SH3D files that can be imported in the `Resources/sample` directory.
Let me attach an FC file imported from `ApartmentWithBowWindow.sh3d`.
[ApartmentWithBowWindow.zip](https://github.com/user-attachments/files/17116407/ApartmentWithBowWindow.zip)
Let me know if that helps you.

**Comment by rostskadat** [comment]
> For example, having streamlined options to display scenes in different rendering engines right within SH3D workbench?
> 
> It may be beneficial to just ping @howetuft directly and ask how other workbenches have utilized RenderWB and even streamlined it's powerful functionality so we don't 'reinvent the wheel' if you will?

Hello @luzpaz ,

I do not quite get the benefit (for the user) to have shortcuts within the S3HD WB to the Render WB, instead of just switching to the Render WB itself. Are you suggesting to have simply a "Render" button in the SH3D WB that would in turn call the rendering command of the Render WB? In that case how the initialization of the Rendering View should happen?

If, instead, you are referring to importing the different cameras and POV found in the SH3D >> `3D view` >> `go to Point of View`, I agree, that would be interesting to have these view pre-configured in FC and be able to render them just with the click of a button.

Have I understood you properly?

**Comment by howetuft** [comment]
Hello,
Made a quick test, fixed a little bug and here is the result:

**LuxCore:**

![image](https://github.com/user-attachments/assets/e2c56ced-667e-4b6e-bb5f-03c42c156565)

**Pov-ray:**

![image](https://github.com/user-attachments/assets/5e3ade30-abac-4245-a59c-ddb77375d5a9)

I attach the modified FCStd.
[ApartmentWithBowWindow.Render.FCStd.zip](https://github.com/user-attachments/files/17129166/ApartmentWithBowWindow.Render.FCStd.zip)
Please update Render WB to last version beforehand.

**Comment by rostskadat** [comment]
Hello @howetuft 

Thanks a lot for taking the time to do these tests. Would you mind expanding a little bit on the bug you fixed, especially if it is a bug related to the import itself?

Regards

**Comment by luzpaz** [comment]
> I do not quite get the benefit (for the user) to have shortcuts within the S3HD WB to the Render WB, instead of just switching to the Render WB itself. Are you suggesting to have simply a "Render" button in the SH3D WB that would in turn call the rendering command of the Render WB? In that case how the initialization of the Rendering View should happen?

You can make Render WB an optional dependency in the [package.xml](https://github.com/rostskadat/FreeCAD-SH3D/blob/main/package.xml) (see [Package Metadata docs](https://wiki.freecad.org/Package_Metadata#.3Cdepend.3E))

> importing the different cameras and POV found in the SH3D >> 3D view >> go to Point of View, I agree, that would be interesting to have these view pre-configured in FC and be able to render them just with the click of a button.

And, yes, that would be a great feature as well.

**Comment by howetuft** [comment]
>  especially if it is a bug related to the import itself?

There is no import in Render. To the contrary, Render _exports_ from FreeCAD to a rendering engine.
The bug was related to the corner case when the exported mesh was empty (it occured in the test file you provided). In this case, an exception was raised but not caught, resulting in a fatal error. The exception is now handled as a non-blocking warning.

**Comment by howetuft** [comment]
> I do not quite get the benefit (for the user) to have shortcuts within the S3HD WB to the Render WB, instead of just switching to the Render WB itself.

Please note I agree with you, @rostskadat!

**Comment by rostskadat** [comment]
Hello @luzpaz 

I have added the creation of a default POVRAY project containing the newly imported Site. Is that one of the feature that you were thinking about?

Regards

**Comment by luzpaz** [comment]
Thanks for your efforts. 
Lets add an optional depedency for RenderWB in package xml
```xml
<!-- Optional install of 3rd-party Render WB to streamline ability to render scenes using various rendering engines -->
<depend type="addon" optional="true">Render Workbench</depend>`
```
Source: https://github.com/FreeCAD/FreeCAD-render/issues/454#issue-2547901211

Hopefully this can inform users who are not aware of RenderWB of its existence.

**Comment by luzpaz** [comment]
My bad, already done in  
https://github.com/rostskadat/FreeCAD-SH3D/blob/68a5de24435568a1add9de18137743bc0d6638f6/package.xml#L23

Closing ticket.
